name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: rodrigo-nogues/github-action-install-atlassian-sdk@v1
      - name: Build Project
        run:  atlas-mvn package